spring:
  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}
      embedding:
        options:
          model-name: text-embedding-v3 # 或者 text-embedding-v3
      chat:
        options:
          model: ${AI_DASHSCOPE_MODEL}
    mcp:
      client:
        enabled:  ${MCP_ENABLE:false}
        sse:
          connections:
            das-mcp:
              sse-endpoint: /sse
              url: ${MCP_URL:http://localhost:8000/} # MCP Server 的 SSE 端点
        request-timeout: 60s
server:
  port: 8081
agent:
  knowledge:
    raw-dir: ${AGENT_RAW_KNOWLEDGE_DIR:src/main/resources/raw-knowledge}
    store-file: ${AGENT_KNOWLEDGE_STORE_FILE:src/main/resources/knowledge/vector-store.json}
    rebuild-on-startup: ${AGENT_KNOWLEDGE_REBUILD:false}
